export const ALL_TESTS_REQUEST = "ALL_TESTS_REQUEST";
export const ALL_TESTS_SUCCESS = "ALL_TESTS_SUCCESS";
export const ALL_TESTS_FAIL = "ALL_TESTS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
