export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_RESET = "UPDATE_USER_RESET";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const RESTORE_PASSWORD_REQUEST = "RESTORE_PASSWORD_REQUEST";
export const RESTORE_PASSWORD_SUCCESS = "RESTORE_PASSWORD_SUCCESS";
export const RESTORE_PASSWORD_RESET = "RESTORE_PASSWORD_RESET";
export const RESTORE_PASSWORD_FAIL = "RESTORE_PASSWORD_FAIL";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

export const UPDATE_USER_LESSON_REQUEST = "UPDATE_USER_LESSON_REQUEST";
export const UPDATE_USER_LESSON_SUCCESS = "UPDATE_USER_LESSON_SUCCESS";
export const UPDATE_USER_LESSON_RESET = "UPDATE_USER_LESSON_RESET";
export const UPDATE_USER_LESSON_FAIL = "UPDATE_USER_LESSON_FAIL";

export const UPDATE_USER_GRADE_REQUEST = "UPDATE_USER_GRADE_REQUEST";
export const UPDATE_USER_GRADE_SUCCESS = "UPDATE_USER_GRADE_SUCCESS";
export const UPDATE_USER_GRADE_RESET = "UPDATE_USER_GRADE_RESET";
export const UPDATE_USER_GRADE_FAIL = "UPDATE_USER_GRADE_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
